export enum IconId {
  FILTER = 'filter',
  ARROW_DOWN = 'arrowDown',
  PIXEMA = 'pixema',
  HOME = 'home',
  TRENDS = 'trends',
  FAVORITES = 'favorites',
  SETTING = 'setting',
  SHARE = 'share',
  ARROW = 'arrow',
  MENU = 'menu',
  CLOSE = 'close',
  USER = 'user',
  ARROW_RIGHT = 'arrowRight',
  CHECK = 'check',
  SPINNER = 'spinner',
  FILM_NONE = 'filmNone',
}